[window]
blur = true
opacity = 0.6

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 12.16

[keyboard]
bindings = [
{ key = "Backspace", mods = "Control", action = "None" },
{ key = "C", mods = "Control|Shift", action = "Copy" },
{ key = "V", mods = "Control|Shift", action = "Paste" }
]

