# Tabs
map alt+shift+n new_tab
map alt+shift+, previous_tab 
map alt+shift+. next_tab 

# Windows
map alt+shift+[ launch --location=hsplit
map alt+shift+] launch --location=vsplit
map alt+shift+q close_window
map alt+shift++ resize_window wider 5
map alt+shift+- resize_window narrower 5

# Switch focus between windows using hjkl
map alt+shift+h neighboring_window left
map alt+shift+j neighboring_window down
map alt+shift+k neighboring_window up
map alt+shift+l neighboring_window right
