# By default, all the folders/files without a path, will be linked to $HOME/.config.
# Files with a path that don't start with "/" will be prefixed with $HOME.
# You can copy files instead of linking them by using "copy" as the third argument.
# ----------------------------------------------------------------------------------
# Examples
# - zsh -> /home/user/.config/zsh
# - zsh:.zsh -> /home/user/.zsh
# - zsh:/etc/zsh -> /etc/zsh
# - zsh:.zsh:copy -> /home/user/.zsh

scripts:scripts
alacritty
hypr
nvim
rofi
tmux
waybar
.zshrc:.zshrc

images/wallpapers:Images:copy
