# By default, all the folders/files without a path, will be linked to $HOME/.config.
# Files with a path that don't start with "/" will be prefixed with $HOME.
# ----------------------------------------------------------------------------------
# Examples
# - zsh -> /home/user/.config/zsh
# - zsh:.zsh -> /home/user/.zsh
# - zsh:/etc/zsh -> /etc/zsh

alacritty
hypr
nvim
tmux
waybar
.zshrc:.zshrc
