#!/bin/bash

max_volume=100

possible_targets_regex="^(sink|source)$"
possible_events_regex="^(toggle_mute|volume_up|volume_down)$"

if [[ ! $1 =~ $possible_targets_regex ]]; then
  echo "Invalid target: $1"
  exit 1
fi

target=$1
uppercased_target=$(echo $target | tr 'a-z' 'A-Z')

if [[ ! $2 =~ $possible_events_regex ]]; then
  echo "Invalid event: $2"
  exit 1
fi

event=$2

current_volume=$(pactl get-$target-volume @DEFAULT_$uppercased_target@ | grep -Po '\d+(?=%)' | head -n 1)

toggle_mute () {
  pactl set-$target-mute @DEFAULT_$uppercased_target@ toggle
}

volume_up () {
  if ((current_volume + 5 < max_volume)); then
    pactl set-$target-volume @DEFAULT_$uppercased_target@ +5%
    return 0
  fi

  pactl set-$target-volume @DEFAULT_$uppercased_target@ 100%
}

volume_down () {
  if ((current_volume == 0)); then
    return 0
  fi

  pactl set-$target-volume @DEFAULT_$uppercased_target@ -5%
}

eval $event
