background = #0a0a0a
foreground = #eeeeee
cursor-color = #fab283
cursor-text = #0a0a0a
selection-background = #1e1e1e
selection-foreground = #eeeeee

palette = 0=#141414
palette = 1=#e06c75
palette = 2=#7fd88f
palette = 3=#e5c07b
palette = 4=#5c9cf5
palette = 5=#9d7cd8
palette = 6=#56b6c2
palette = 7=#eeeeee
palette = 8=#323232
palette = 9=#e06c75
palette = 10=#7fd88f
palette = 11=#ffc09f
palette = 12=#fab283
palette = 13=#9d7cd8
palette = 14=#56b6c2
palette = 15=#eeeeee

