# Set windows and panes first indexes to be 1 instead of 0
set -g base-index 1
set-window-option -g pane-base-index 1

# Set vi mode as default
set-window-option -g mode-keys vi

# --- Key bindings ---

# Unbind all keys
unbind-key -a
unbind-key -a -T root

# Ctrl+Space to prefix
set -g prefix C-Space

# r to source changes on tmux.conf
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded ~/tmux.conf"

# n, k and t to create, kill and rename windows
bind n new-window -c "#{pane_current_path}"
bind k killw
bind t command-prompt "rename-window '%%'"

# Alt + ,. to navigate between windows
bind -n M-, previous-window
bind -n M-. next-window

# v and h to split panes vertically and horizontally
bind v split-window -h -c "#{pane_current_path}"
bind h split-window -v -c "#{pane_current_path}"

# x to kill panes
bind x killp

# Ctrl + hjkl vim motions to navigate between panes
bind -n C-h select-pane -L
bind -n C-j select-pane -D
bind -n C-k select-pane -U
bind -n C-l select-pane -R

